### ISSUE TITLE
any example around?

### ISSUE THREAD

**Issue by moebiussurfing** [jonasfehr/ofxMidiDevice#1]
hey thanks for share. do you have any example to check around?

**Comment by jonasfehr** [comment]
Hi Moebiussurfing,
I just dig into creating an example for you. But the addon is not finished, and I got into some complicated boundries as well. It still needs work to become more handy for other users. But you are welcome to look at the implementation I use it for, where I use a motorfader controller, together with MadMapper, to control different parameter pages in my setup:
[https://github.com/jonasfehr/MadMapperControl](https://github.com/jonasfehr/MadMapperControl)


Meanwhile, I would suggest to take a look at, which seams to have a similar idea behind:
[https://github.com/NickHardeman/ofxMidiParams](https://github.com/NickHardeman/ofxMidiParams)

**Comment by jonasfehr** [comment]
So, i did some work, and added an example. I hope it's understandable. I don't have any midi controller with me at the moment, so the input channel and CC/Note nr. needs to be corrected, but it should work as such.

**Comment by moebiussurfing** [comment]
cool thanks @jonasfehr , 
yes I used https://github.com/NickHardeman/ofxMidiParams previously and it's fine. There's another one too roymacdonald/ofxParameterMidiSync.
so your idea is to have all controls (pages and feedback too) of a midi device mapped to ofParameters, right?

**Comment by moebiussurfing** [comment]
..it's interesting the use of OscQuery to make all the linking to midi easier

**Comment by jonasfehr** [comment]
Hi, Yes, I created the addon, with the idea to create a dynamic mapping of midi parameters. the mapping to ofParameters is just one possibility. You can also use the midiComponents.value directly. As everything is normalized, it's quite easy to use.  One of the major goals was to create instant feedback, therefore changing the value results in a feedback on the same midi "address" as the incoming signal. As i set it up, the feedback is activated by default, but you can disable it by setting the variable doFeedback in the midiComponents to false.

What do you want to use the addon for? You are wellcome to develop it further.

**Comment by moebiussurfing** [comment]
thanks for reply. i was just curious. 
my interest is about easy adding to the app control and feedback with midi (and osc). I tried your example and is cool, your feedback thing works fine. ofxMidiParams is cool also because it has midi learn for parameters, but has no feedback (midi out). 
(For osc thing I am using https://github.com/2bbb/ofxPubSubOsc, I never tried the OSCquery in detail.)

**Comment by jonasfehr** [comment]
Hi, 
Yes, a midi learn function could be lovely, though, as I don't use it necessarily with ofParameters, it's difficult to add. What could be added is a function, which detects automatically what tipe of input is used, and creates a new component accordingly. That wouldn't be much of work.
I hope you can use my work.
